import { linksMenus } from './links-menu.interface';

export const ROUTES: linksMenus[] = [
    {
        path: '/inicio',
        titulo: 'Início',
        icon: 'ft-home',
        class: '',
        autoridades: [],
        submenu: [],
    },
    // {
    //     path: '/servicos',
    //     titulo: 'Serviços',
    //     icon: 'ft-tag',
    //     class: '',
    //     autoridades: [],
    //     submenu: [
    //         {
    //             path: '/inicio/peritos',
    //             titulo: 'Consulta',
    //             icon: '',
    //             class: '',
    //             autoridades: [],
    //             submenu: [],
    //         },
    //         {
    //             path: '/atendimentos',
    //             titulo: 'Requerimento',
    //             icon: '',
    //             class: '',
    //             autoridades: [],
    //             submenu: [],
    //         },
    //     ],
    // },
    {
        path: '/partituras',
        titulo: 'Partituras',
        icon: 'ft-file-text',
        class: '',
        autoridades: [],
        submenu: [],
    },
    {
        path: '/servidores',
        titulo: 'Compositores',
        icon: 'ft-users',
        class: '',
        autoridades: [],
        submenu: [],
    },
    {
        path: '/servidores',
        titulo: 'Gêneros',
        icon: 'ft-tag',
        class: '',
        autoridades: [],
        submenu: [],
    },
    {
        path: '/servidores',
        titulo: 'Temas',
        icon: 'ft-grid',
        class: '',
        autoridades: [],
        submenu: [],
    },
    {
        path: '/servidores',
        titulo: 'Intrumentos',
        icon: 'ft-music',
        class: '',
        autoridades: [],
        submenu: [],
    },
    {
        path: '/usuarios',
        titulo: 'Usuários',
        icon: 'ft-user',
        class: '',
        autoridades: [],
        submenu: [],
    },
];
